### ISSUE TITLE
How to access superpixel information

### ISSUE THREAD

**Issue by alexandru-lesi** [carlren/gSLIC2#14]
Hey there,

I can't figure out how to access the superpixel result correctly. I don't need the drawn output image itself but the actual superpixel information. I basically want to store the superpixel ID for each pixel as a 4th channel in the image. Is there no trivial way to do this, or am I just missing something? I also need a way to determine neighboring superpixels, if it's possible.

Best,
Alex

**Comment by carlren** [comment]
if you press <kbd>s</kbd> while running the demo, it will save the index information to a png image.
```
gSLICr_engine->Write_Seg_Res_To_PGM(out_name);
```
is the function that you want to look at.

Since gSLICr currently only operate on 4-channel 8 bits/channel image, unless you have less than 256 superpxiels, the 4-th channel of the image won't be enough to save the index map.

**Comment by abhiyad** [comment]
Hey @carlren  , 
I am new to gSLICr , basically I want to do the averaging over all pixels which lie inside a SuperPixel.
Is there any way to do it ? ? 

I also want the matrix which has labels for each pixel not just the image itself , Please tell me how can I achieve this ?? 

Regards,
Abhishek
